<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('dashboard');
		} else if ($this->session->userdata('login') && $this->session->userdata('login') == true)
		{
			redirect('dashboard');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('login');
		}
		else
		{

			$cek_login=$this->model->cek_login(
					$this->input->post('username'),
					$this->input->post('password')
			);

			$level=set_value('level',$cek_login->level);
			$nama=set_value('nama',$cek_login->nama);

			if(!empty($cek_login) and $level=='member')
			{
				$this->session->set_userdata('logined', true);
				$this->session->set_userdata('username',$cek_login->username);
				$this->session->set_userdata('level',$level);
				$this->session->set_userdata('nama',$nama);
				redirect(site_url('dashboard'));

			} else if (!empty($cek_login) and $level=='admin') {
				$this->session->set_userdata('login', true); 
				$this->session->set_userdata('username',$cek_login->username);
				$this->session->set_userdata('level',$level);
				$this->session->set_userdata('nama',$nama);
				redirect(site_url('dashboard'));
			}
			else 
			{
				redirect("/"); 
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect("/");
    } 

    public function adminlogout()
    {
		$this->session->unset_userdata('login');
		redirect("/"); 
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */